### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by NicolasDorier** [ericsink/wasm2cil#1]
Is there any instruction somewhere on how to use your project?

I would like to try on this module: https://aois.blob.core.windows.net/public/secp256k1.wasm

**Comment by ericsink** [comment]
Sorry, no documentation yet.  :-)

But if you want to just try converting a module, the console app in c-testsuite/build is currently configured to do that.  It wants two command line args.  The first is the path to your wasm file.  The second is the destination to write the assembly.

    dotnet run foo.wasm foo.dll

But I just tried the module you linked, and it doesn't work.  :-(

Looks like this issue is another instance of RyanLamansky/dotnet-webassembly#11

I don't have table imports working yet either.

And if I did, there would also be the minor problem of needing a reference assembly for the other imports.  That's not a big issue, but the console app mentioned above is currently configured only to provide WASI.

**Comment by NicolasDorier** [comment]
@ericsink what is a "table import"? I thought it was something needed for pulling external dependencies. However, this lib, `secp256k1` should be pure C without dependencies, which does not even have heap allocation (no malloc/free).

**Comment by ericsink** [comment]
In Wasm, a "table" is a used for indirect function calls.  Like a "vtable".  Conceptually, it's a list of function pointers, and the call indirect instruction is saying "call the nth function in this list".

What produced this Wasm file?  Where did it come from?

**Comment by NicolasDorier** [comment]
@ericsink this file has been generated by this dockerfile

https://github.com/bitauth/bitcoin-ts/blob/master/wasm/docker/secp256k1.Dockerfile

The project itself is https://github.com/bitcoin-core/secp256k1 which is a pure minimalist cryptographic library made in C without dependency.

**Comment by ericsink** [comment]
Ah, I see.

I'm guessing the table import isn't necessary.  

So my code currently can't cope with the kinds of Wasm produced by emsdk.  But the original C code here looks very straightforward, so it should be possible to get it compiling with clang-8 and wasi-sysroot, which should result in something I can convert to an assembly.

**Comment by ericsink** [comment]
That code appears to also have a dependency on gmp.

**Comment by NicolasDorier** [comment]
Interesting. I will try to make it works with clang-8.

**Comment by NicolasDorier** [comment]
If I include gmp statically should be OK. Though I am surprised about this dependency.

**Comment by NicolasDorier** [comment]
@ericsink I am trying to build the library with the wasi-sdk

You can see my progress on https://github.com/NicolasDorier/NBitcoin.Secp256k1

It build but I am surprised because there is no wasm file created anywhere...
But it still seems to use clang under the hood.

I think this library is a good test for your project, because it has no dependency (if I turn bignum feature off)

**Comment by NicolasDorier** [comment]
There is `libsecp256k1_la-secp256k1.o` that is generated, but I doubt this is what is needed.

**Comment by NicolasDorier** [comment]
So I am getting a `libsecp256k1.a` checking if it is wasm... I am surprised it does not have the `.wasm` extension.

**Comment by NicolasDorier** [comment]
sadly, it is not a wasm file :(

**Comment by ericsink** [comment]
Yeah, I'm not sure how all that autoconf/configure stuff interacts with the need to use --sysroot and --target flags.

**Comment by NicolasDorier** [comment]
I managed to build the wasm file!

https://aois.blob.core.windows.net/public/libsecp256k1.wasm

It seems to be working with RyanLamansky/dotnet-webassembly as well!! :)
Will try your project (you can see how I did on my repo)

**Comment by NicolasDorier** [comment]
So

```
Unhandled Exception: System.Exception: import global not found: env.__stack_pointer
   at wasm.import.import_global(ModuleDefinition md, ImportedGlobal s, Assembly a) in C:\Sources\wasm2cil\wasm\Import.fs:line 63
   at wasm.cecil.prep@1021.Invoke(Int32 i, GlobalLookupItem gi) in C:\Sources\wasm2cil\wasm\Cecil.fs:line 1025
   at Microsoft.FSharp.Collections.ArrayModule.MapIndexed[T,TResult](FSharpFunc`2 mapping, T[] array)
   at wasm.cecil.create_globals[a](ModuleIndex ndx, BasicTypes bt, ModuleDefinition md, FSharpOption`1 env_assembly) in C:\Sources\wasm2cil\wasm\Cecil.fs:line 1032
   at wasm.cecil.gen_assembly(Target target, Module m, String assembly_name, String ns, String classname, Version ver, Stream dest) in C:\Sources\wasm2cil\wasm\Cecil.fs:line 1548
   at Program.main(String[] argv) in C:\Sources\wasm2cil\c-testsuite\build\Program.fs:line 34
```

**Comment by NicolasDorier** [comment]
Still a bunch of import:
That's strange.
```
Imports:
__indirect_function_table
__stack_pointer
__memory_base
__table_base
fd_prestat_get
fd_prestat_dir_name
environ_sizes_get
environ_get
args_sizes_get
args_get
main
proc_exit
fd_fdstat_get
fd_close
fd_seek
fd_write
```

**Comment by NicolasDorier** [comment]
Nowhere in my lib source code I see any reference to all of this.

**Comment by NicolasDorier** [comment]
Ok I managed to remove some by making sure the linker does not create an entry point: Still have
```
__indirect_function_table
__stack_pointer
__memory_base
__table_base
fd_close
fd_seek
fd_write
```

**Comment by NicolasDorier** [comment]
I checked the [wat file](https://aois.blob.core.windows.net/public/libsecp256k1.wat) those imports are not referenced by any code my library is exporting :(

**Comment by ericsink** [comment]
Most of those imports are basic calls from the WASI API.

**Comment by ericsink** [comment]
The "env" __ imports are a surprise.  I'm not sure why they're showing up.  Usually that stuff shows up with Clang when I'm not building with the wasi target, but *with* the wasi target, only the wasi functions get declared as imports.

It is interesting to note that __indirect_function_table is a table import, which is the problem we started with.

**Comment by NicolasDorier** [comment]
It seems that it depends on your version. See

![image](https://user-images.githubusercontent.com/3020646/56845821-171ae380-6902-11e9-8717-3517d9ffd380.png)

https://reviews.llvm.org/D40875

The `fd_` are a surprise to me as those does not seem to be used at all in the wat

**Comment by NicolasDorier** [comment]
`(import "wasi_unstable" "fd_close" (func $__wasi_fd_close (type 4)))` oh I get it they are indeed provided by wasi.

> Usually that stuff shows up with Clang when I'm not building with the wasi target, but with the wasi target, only the wasi functions get declared as imports.

I don't understand, as far as I understood your blog post, by using `clang --sysroot=/opt/wasi-sdk/share/sysroot --target=wasm32-unknown-wasi`, I thought that wasi would statically compile any missing symbol like malloc/free. Why `fd_*` are not included?

**Comment by NicolasDorier** [comment]
Actually I just tracked `fd_` to some `printf` call. I can just comment those.

**Comment by NicolasDorier** [comment]
Latest: [wat](https://aois.blob.core.windows.net/public/libsecp256k1.wat) and [wasm](https://aois.blob.core.windows.net/public/libsecp256k1.wasm).

The only imports remaining are
```
  (import "env" "__indirect_function_table" (table (;0;) 4 funcref))
  (import "env" "__stack_pointer" (global (;0;) (mut i32)))
  (import "env" "__memory_base" (global (;1;) i32))
  (import "env" "__table_base" (global (;2;) i32))
```

If you can fix this, then things would work like expected :)

**Comment by NicolasDorier** [comment]
As far as `__stack_pointer` is concerned the reference is here https://reviews.llvm.org/D34172 I am quite unsure about what it means.

**Comment by Serentty** [comment]
I'm trying to build with .NET 5.0 preview, and if I change the version in the project to get it to build, I get this:

```
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at Mono.Cecil.ModuleParameters.GetCurrentRuntime()
   at Mono.Cecil.ModuleParameters..ctor()
```
